### ISSUE TITLE
compile error, missing symbol CycloneJumpTab

### ISSUE THREAD

**Issue by rdaum** [notaz/cyclone68000#1]
The generated Cyclone.h declares CycloneJumpTab extern long[]
but Cyclone.S does not have it in its .global

This seems to make the linker (arm-none-eabi-g++ 7.3.1 20180622) unhappy:

main.cc:(.text+0xa04): undefined reference to `CycloneJumpTab'

Adding it to the .global section of Cyclone.S seems to fix the link problem.

**Comment by notaz** [comment]
Thanks for the report, should be fixed in 5fc93bddb71461abb7619cf506d6f15ba8a675f3.
